[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'scrooloose/nerdcommenter.git'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'yuroyoro/vim-autoclose'

[[plugins]]
repo = 'c9s/cascading.vim'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'godlygeek/tabular'

[[plugins]]
repo = 'h1mesuke/vim-alignta'

[[plugins]]
repo = 'LeafCage/yankround.vim'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'taku-o/vim-toggle'

[[plugins]]
repo = 'slim-template/vim-slim'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'mattn/gist-vim'

[[plugins]]
repo = 'osyo-manga/vim-over'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertCharPre'
hook_source = '''
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#auto_complete_delay = 0
  let g:deoplete#auto_complete_start_length = 1
  let g:deoplete#enable_camel_case = 0
  let g:deoplete#enable_ignore_case = 0
  let g:deoplete#enable_refresh_always = 0
  let g:deoplete#enable_smart_case = 1
  let g:deoplete#file#enable_buffer_path = 1
  let g:deoplete#max_list = 10000
  inoremap <expr><tab> pumvisible() ? "\<C-n>" :
        \ neosnippet#expandable_or_jumpable() ?
        \    "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
'''
on_i = 1

[[plugins]]
repo = 'ujihisa/neco-ruby'

[[plugins]]
repo = 'ujihisa/neco-look'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'tyru/open-browser-github.vim'

[[plugins]]
repo = 'nazo/pt.vim'

[[plugins]]
repo = 'othree/javascript-libraries-syntax.vim'

[[plugins]]
repo = 'dag/vim-fish'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'thinca/vim-ref'

[[plugins]]
repo = 'vim-ruby/vim-ruby'

[[plugins]]
repo = 'tpope/vim-rails'

[[plugins]]
repo = 'tpope/vim-markdown'

[[plugins]]
repo = 'kchmck/vim-coffee-script'

[[plugins]]
repo = 'yuroyoro/vim-python'

[[plugins]]
repo = 'yuroyoro/vim-scala'

[[plugins]]
repo = 'jondistad/vimclojure'

[[plugins]]
repo = 'eagletmt/ghcmod-vim'

[[plugins]]
repo = 'vim-syntastic/syntastic'

[[plugins]]
repo = 'isRuslan/vim-es6'

[[plugins]]
repo = 'vim-scripts/minibufexpl.vim'

[[plugins]]
repo = 'vim-scripts/The-NERD-tree'

[[plugins]]
repo = 'vim-scripts/vtreeexplorer'

[[plugins]]
repo = 'banyan/recognize_charcode.vim'

[[plugins]]
repo = 'tyru/vim-altercmd'

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'tyru/urilib.vim'

[[plugins]]
repo = 'thinca/vim-openbuf'

[[plugins]]
repo = 'yuroyoro/vimdoc_ja'

[[plugins]]
repo = 'tsukkee/lingr-vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'Lokaltog/vim-powerline'

[[plugins]]
repo = 'mattn/vim-metarw-redmine'

[[plugins]]
repo = 'kana/vim-metarw'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'motemen/git-vim'

[[plugins]]
repo = 'vim-scripts/dbext.vim'

[[plugins]]
repo = 'vim-scripts/YankRing.vim'

[[plugins]]
repo = 'sorah/unite-ghq'

[[plugins]]
repo = 'terryma/vim-multiple-cursors'

[[plugins]]
repo = 'szw/vim-tags'

[[plugins]]
repo = 'vim-scripts/taglist.vim'

[[plugins]]
repo = 'jlanzarotta/bufexplorer'

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'tsukkee/unite-help'

[[plugins]]
repo = 'h1mesuke/unite-outline'

[[plugins]]
repo = 'basyura/unite-rails'

[[plugins]]
repo = 'thinca/vim-unite-history'

[[plugins]]
repo = 'tsukkee/unite-tag'

[[plugins]]
repo = 'choplin/unite-vim_hacks'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'yuroyoro/yuroyoro256.vim'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'alpaca-tc/beautify.vim'

[[plugins]]
repo = 'kmnk/vim-unite-giti'

[[plugins]]
repo = 'https://gist.github.com/tamanobi/3cb51380e10a9231c7aed15894ef5be0'
script_type='plugin'

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo = 'heavenshell/vim-tslint-config'

[[plugins]]
repo = 'vim-scripts/haml.zip'

[[plugins]]
repo = 'vim-scripts/cecutil'

[[plugins]]
repo = 'vim-scripts/Align'

[[plugins]]
repo = 'vim-scripts/nginx.vim'

[[plugins]]
repo = 'vim-scripts/camelcasemotion'

[[plugins]]
repo = 'kassio/neoterm'

[[plugins]]
repo = 'mattn/vim-sonots'

[[plugins]]
repo = 'tpope/vim-abolish'

[[plugins]]
repo = 'tyru/operator-camelize.vim'

[[plugins]]
repo = 'kana/vim-operator-user'
