#!/usr/bin/env sh

# Print Colored messages
# ---------------------------------------------------**
logging() {
  local yellow="33"
  local blue="34"
  local turquoise="36"
  local white="37"
  local red="31"
  local text="$2"
  local _color=

  case "$1" in
   "message") _color=$yellow ;;
   "warn") _color=$red ;;
   "succeed") _color=$blue ;;
   "fail") _color=$green ;;
  esac

  printf "\033[${_color}m${text}\033[m\n"
}

message() {
  logging "$0" "$@"
}

warn() {
  logging "$0" "$@"
}

succeed() {
  logging "$0" "$@"
}

fail() {
  logging "$0" "$@"
}

# Ask
# ---------------------------------------------------**
ask() {
  logging "$0" "$@"
}

# Utilities
# ---------------------------------------------------**
command_exists(){
  type $1 &> /dev/null
}

command_not_exists() {
  ! type $1 &> /dev/null
}
