# Using my helpers
# ---------------------------------------------------**
. "$HOME/.helpers"

# Load plugins
# ---------------------------------------------------**
. "$HOME/.zplug/zplug"
. "$HOME/.tmux/tmuxinator.zsh"

# Configuration files for use in Zsh
# ---------------------------------------------------**
. "$HOME/.zshrc.env"
. "$HOME/.zshrc.config"
. "$HOME/.zshrc.setting"
. "$HOME/.zshrc.alias"
. "$HOME/.zshrc.function"
. "$HOME/.zshrc.plugins"
. "$HOME/.zshrc.local"

# When OSX or Linux
# ---------------------------------------------------**
case "${OSTYPE}" in
  darwin*)
    . "$HOME/.zshrc.osx"
    ;;

  linux*)
    . "$HOME/.zshrc.linux"
    ;;
esac
