. ~/dotfiles/tmux/tmuxinator.zsh
. ~/dotfiles/zsh/zsh-bd/bd.zsh
. ~/dotfiles/zsh.dot/zshrc.env
. ~/dotfiles/zsh.dot/zshrc.config
. ~/dotfiles/zsh.dot/zshrc.setting
. ~/dotfiles/zsh.dot/zshrc.color
. ~/dotfiles/zsh.dot/zshrc.alias
. ~/dotfiles/zsh.dot/zshrc.function
. ~/dotfiles/zsh.dot/zshrc.local

case "${OSTYPE}" in
  darwin*)
    . ~/dotfiles/zsh.dot/zshrc.osx
    ;;

  linux*)
    . ~/dotfiles/zsh.dot/zshrc.linux
    ;;
esac
